import { ROWS, COLS, applyMove, checkWin, getLegalMoves } from "./core.js";
import { createPolicyModel, deserializePolicy, serializePolicy, newBoard, policyForward, choosePolicyMove, chooseSolverMove, chooseEngineRandomMove, chooseRandomMove, solverScores } from "./solver-core.js";

const STORAGE_KEY="connect4.solverPolicy.v1", HISTORY_KEY="connect4.solverPolicy.benchmarks.v1";
const $=id=>document.getElementById(id);
const els={status:$("appStatus"),board:$("board"),columns:$("columnMoves"),gameStatus:$("gameStatus"),red:$("redPlayer"),yellow:$("yellowPlayer"),newGame:$("newGameBtn"),moveReadout:$("moveReadout"),save:$("saveBtn"),export:$("exportBtn"),import:$("importInput"),reset:$("resetBtn"),positions:$("positionsInput"),depth:$("depthInput"),lr:$("learningRateInput"),train:$("trainBtn"),quick:$("quickTrainBtn"),stop:$("stopBtn"),trainState:$("trainState"),progress:$("trainProgress"),trainStats:$("trainStats"),benchmark:$("benchmarkBtn"),benchmarkStatus:$("benchmarkStatus"),benchmarkOpponent:$("benchmarkOpponent"),benchmarkGames:$("benchmarkGames"),benchmarkStats:$("benchmarkStats"),benchmarkCanvas:$("benchmarkCanvas"),networkCanvas:$("networkCanvas"),weightsCanvas:$("weightsCanvas"),layer:$("layerSelect"),neuron:$("neuronInput"),neuronOutput:$("neuronOutput"),neuronStats:$("neuronStats"),activationRows:$("activationRows"),refresh:$("refreshBtn")};
let model=loadModel(), board=newBoard(), player=1, gameOver=false, autoToken=0, trainingWorker=null, benchmarkWorker=null;
let history=loadHistory();

function loadModel(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?deserializePolicy(JSON.parse(raw)):createPolicyModel();}catch(error){console.error(error);return createPolicyModel();}}
function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");}catch{return[];}}
function saveModel(){localStorage.setItem(STORAGE_KEY,JSON.stringify(serializePolicy(model)));els.status.textContent=`Saved ${model.training.positions.toLocaleString()} labeled positions`;}
function setModel(next){model=next;saveModel();renderAll();}
function playerKind(){return player===1?els.red.value:els.yellow.value;}
function label(kind){return {human:"Human",solver:"Solver",ai:"AI",random:"Random","engine-random":"Engine + random"}[kind];}
function choose(kind){if(kind==="ai")return choosePolicyMove(model,board,player);if(kind==="solver")return chooseSolverMove(board,player,5);if(kind==="engine-random")return chooseEngineRandomMove(board,player);return chooseRandomMove(board);}

function renderBoard(){
  const cells=[];for(let r=ROWS-1;r>=0;r--)for(let c=0;c<COLS;c++){const value=board[r*COLS+c];cells.push(`<div class="cell ${value===1?"red":value===-1?"yellow":""}"></div>`);}els.board.innerHTML=cells.join("");
  const legal=getLegalMoves(board), human=!gameOver&&playerKind()==="human";
  els.columns.innerHTML=Array.from({length:7},(_,c)=>`<button data-col="${c}" ${human&&legal.includes(c)?"":"disabled"} aria-label="Play column ${c+1}">${c+1}</button>`).join("");
  els.columns.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>playMove(Number(button.dataset.col))));
}

function renderGameInfo(){
  if(!gameOver)els.gameStatus.textContent=`${player===1?"Red":"Yellow"} to move - ${label(playerKind())}`;
  const result=policyForward(model,board,player), legal=getLegalMoves(board);let scores=[];
  try{scores=solverScores(board,player,3);}catch{scores=Array(7).fill(null);}
  let best=null;for(const c of legal)if(best===null||result.probabilities[c]>result.probabilities[best])best=c;
  els.moveReadout.innerHTML=Array.from({length:7},(_,c)=>`<div class="move-score ${c===best?"best":""}"><b>${c+1}</b><br>${legal.includes(c)?(result.probabilities[c]*100).toFixed(1)+"%":"--"}<br><span>${scores[c]===null?"--":scores[c]}</span></div>`).join("");
}

function playMove(col){if(gameOver||!getLegalMoves(board).includes(col))return;const moving=player,row=applyMove(board,col,moving);if(checkWin(board,row,col,moving)){gameOver=true;els.gameStatus.textContent=`${moving===1?"Red":"Yellow"} wins (${label(moving===1?els.red.value:els.yellow.value)})`;}else if(!getLegalMoves(board).length){gameOver=true;els.gameStatus.textContent="Draw";}else player=-player;renderAll();scheduleAuto();}
function newGame(){autoToken++;board=newBoard();player=1;gameOver=false;renderAll();scheduleAuto();}
function scheduleAuto(){const token=++autoToken;if(gameOver||playerKind()==="human")return;setTimeout(()=>{if(token!==autoToken||gameOver)return;playMove(choose(playerKind()));},260);}

function statRows(rows){return rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join("");}
function renderTraining(){const t=model.training;els.trainStats.innerHTML=statRows([["Labeled positions",t.positions.toLocaleString()],["Training runs",t.epochs],["Last loss",t.averageLoss.toFixed(4)],["Teacher agreement",`${(t.teacherAgreement*100).toFixed(1)}%`],["Last solver depth",t.solverDepth||"-"]]);}

function startTraining(override){if(trainingWorker)return;const positions=override||Math.max(100,Math.min(200000,Number(els.positions.value)||12000));trainingWorker=new Worker("./src/solver-trainer-worker.js",{type:"module"});els.train.disabled=els.quick.disabled=true;els.stop.disabled=false;els.trainState.textContent="Generating + learning";els.progress.value=0;els.status.textContent=`Solver labeling ${positions.toLocaleString()} positions`;
  trainingWorker.onmessage=e=>{const data=e.data;if(data.type==="progress"){els.progress.value=data.completed/data.total;els.trainState.textContent=data.stage||"Generating + learning";els.trainStats.innerHTML=statRows([["Stage progress",data.completed.toLocaleString()+" / "+data.total.toLocaleString()],["Live loss",data.loss?data.loss.toFixed(4):"-"],["Live agreement",data.agreement?`${(data.agreement*100).toFixed(1)}%`:"-"]]);}else if(data.type==="done"){model=deserializePolicy(data.model);finishTraining(data.stopped?"Training stopped":"Training complete");saveModel();renderAll();}else if(data.type==="error"){finishTraining(`Training error: ${data.message}`);}};
  trainingWorker.onerror=e=>finishTraining(`Training error: ${e.message}`);trainingWorker.postMessage({type:"train",model:serializePolicy(model),positions,depth:Number(els.depth.value),learningRate:Number(els.lr.value)});
}
function finishTraining(message){trainingWorker?.terminate();trainingWorker=null;els.train.disabled=els.quick.disabled=false;els.stop.disabled=true;els.trainState.textContent="Idle";els.status.textContent=message;}

function runBenchmark(){if(benchmarkWorker)return;const games=Math.max(20,Math.min(2000,Number(els.benchmarkGames.value)||200)),opponent=els.benchmarkOpponent.value;benchmarkWorker=new Worker("./src/solver-benchmark-worker.js",{type:"module"});els.benchmark.disabled=true;els.benchmarkStatus.textContent=`Running ${games} games...`;benchmarkWorker.onmessage=e=>{if(e.data.type!=="done")return;const result={...e.data.result,positions:model.training.positions,createdAt:Date.now()};history.push(result);history=history.slice(-60);localStorage.setItem(HISTORY_KEY,JSON.stringify(history));benchmarkWorker.terminate();benchmarkWorker=null;els.benchmark.disabled=false;renderBenchmark(result);};benchmarkWorker.onerror=e=>{els.benchmarkStatus.textContent=e.message;benchmarkWorker.terminate();benchmarkWorker=null;els.benchmark.disabled=false;};benchmarkWorker.postMessage({type:"benchmark",model:serializePolicy(model),games,opponent});}
function renderBenchmark(last=history.at(-1)){
  if(last){els.benchmarkStatus.textContent=`Last: ${(last.score*100).toFixed(1)}% score vs ${label(last.opponent)}`;els.benchmarkStats.innerHTML=statRows([["Wins",last.wins],["Draws",last.draws],["Losses",last.losses],["Score",`${(last.score*100).toFixed(1)}%`]]);}else els.benchmarkStats.innerHTML="";
  const canvas=els.benchmarkCanvas,ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,pad=34;ctx.clearRect(0,0,w,h);ctx.fillStyle="#141a1d";ctx.fillRect(0,0,w,h);ctx.font="11px system-ui";ctx.strokeStyle="#39444a";ctx.fillStyle="#9eabb1";for(let i=0;i<=4;i++){const y=12+(h-40)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-8,y);ctx.stroke();ctx.fillText(`${100-i*25}%`,2,y+4);}if(!history.length)return;const points=history.slice(-40),maxPos=Math.max(...points.map(p=>p.positions),1),minPos=Math.min(...points.map(p=>p.positions));ctx.strokeStyle="#55b982";ctx.lineWidth=3;ctx.beginPath();points.forEach((p,i)=>{const x=pad+((p.positions-minPos)/Math.max(1,maxPos-minPos))*(w-pad-12),y=12+(1-p.score)*(h-40);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle="#9eabb1";ctx.fillText("labeled positions",w/2-38,h-7);
}

function renderNetwork(){
  const canvas=els.networkCanvas,ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const xs=[30,180,335,490],counts=[12,14,12,7],names=["98 inputs","96 ReLU","64 ReLU","7 softmax"];
  ctx.globalAlpha=.15;ctx.strokeStyle="#63b9d2";for(let l=0;l<3;l++)for(let a=0;a<counts[l];a++)for(let b=0;b<counts[l+1];b+=2){ctx.beginPath();ctx.moveTo(xs[l],35+a*190/Math.max(1,counts[l]-1));ctx.lineTo(xs[l+1],35+b*190/Math.max(1,counts[l+1]-1));ctx.stroke();}ctx.globalAlpha=1;for(let l=0;l<4;l++){for(let n=0;n<counts[l];n++){ctx.beginPath();ctx.arc(xs[l],35+n*190/Math.max(1,counts[l]-1),l===3?6:4,0,Math.PI*2);ctx.fillStyle=l===3?"#55b982":"#dbe4e7";ctx.fill();}ctx.fillStyle="#9eabb1";ctx.font="11px system-ui";ctx.textAlign="center";ctx.fillText(names[l],xs[l],256);}renderWeights();renderActivations();
}
function renderWeights(){const li=Number(els.layer.value),layer=model.layers[li];els.neuron.max=layer.outputSize-1;const neuron=Math.min(Number(els.neuron.value),layer.outputSize-1);els.neuron.value=neuron;els.neuronOutput.value=neuron;const values=layer.weights.slice(neuron*layer.inputSize,(neuron+1)*layer.inputSize),canvas=els.weightsCanvas,ctx=canvas.getContext("2d"),cols=li===0?14:Math.ceil(Math.sqrt(values.length)),rows=Math.ceil(values.length/cols),cw=canvas.width/cols,ch=canvas.height/rows,max=Math.max(...values.map(Math.abs),.001);for(let i=0;i<cols*rows;i++){const v=values[i]||0,intensity=Math.round(35+Math.abs(v)/max*220);ctx.fillStyle=v>=0?`rgb(25,${intensity},110)`:`rgb(${intensity},55,65)`;ctx.fillRect((i%cols)*cw,Math.floor(i/cols)*ch,cw+.5,ch+.5);}const mean=values.reduce((a,b)=>a+b,0)/values.length,norm=Math.sqrt(values.reduce((a,b)=>a+b*b,0));els.neuronStats.innerHTML=statRows([["Selected",li===2?`Output column ${neuron+1}`:`Layer ${li+1}, neuron ${neuron}`],["Bias",layer.biases[neuron].toFixed(5)],["Weight mean",mean.toFixed(5)],["L2 norm",norm.toFixed(4)],["Green / red","positive / negative"]]);}
function renderActivations(){const f=policyForward(model,board,player),groups=[["input",f.activations[0]],["hidden1",f.activations[1]],["hidden2",f.activations[2]],["output",f.probabilities]],rows=[];for(const [name,values] of groups){let max=-Infinity,index=0;for(let i=0;i<values.length;i++)if(values[i]>max){max=values[i];index=i;}const display=name==="output"?max:Math.min(1,max);rows.push(`<div class="activation-row"><span>${name}[${index}]</span><div class="activation-bar"><div class="activation-fill" style="width:${Math.max(0,display)*100}%"></div></div><span>${max.toFixed(4)}</span></div>`);}els.activationRows.innerHTML=rows.join("");}
function renderAll(){renderBoard();renderGameInfo();renderTraining();renderBenchmark();renderNetwork();}

els.newGame.addEventListener("click",newGame);els.red.addEventListener("change",newGame);els.yellow.addEventListener("change",newGame);els.save.addEventListener("click",saveModel);els.reset.addEventListener("click",()=>{if(confirm("Reset all solver-trained weights and training stats?")){localStorage.removeItem(STORAGE_KEY);model=createPolicyModel();newGame();els.status.textContent="Model reset to random weights";}});els.export.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(serializePolicy(model),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`connect4-solver-policy-${model.training.positions}.json`;a.click();URL.revokeObjectURL(url);});els.import.addEventListener("change",()=>{const file=els.import.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{setModel(deserializePolicy(JSON.parse(reader.result)));els.status.textContent=`Imported ${model.training.positions.toLocaleString()} positions`;}catch(e){alert(e.message);}};reader.readAsText(file);});els.train.addEventListener("click",()=>startTraining());els.quick.addEventListener("click",()=>startTraining(2000));els.stop.addEventListener("click",()=>trainingWorker?.postMessage({type:"stop"}));els.benchmark.addEventListener("click",runBenchmark);els.layer.addEventListener("change",()=>{els.neuron.value=0;renderWeights();});els.neuron.addEventListener("input",renderWeights);els.refresh.addEventListener("click",renderNetwork);
renderAll();scheduleAuto();
