import { ROWS, COLS, applyMove, checkWin, getLegalMoves } from "./core.js";
import { createPolicyModel, deserializePolicy, serializePolicy, newBoard, policyForward, choosePolicyMove, chooseSolverMove, chooseEngineRandomMove, chooseRandomMove, solverScores, modelLayers, parameterCount } from "./solver-core.js";

const STORAGE_KEY="connect4.solverPolicy.v2", HISTORY_KEY="connect4.solverPolicy.benchmarks.v2";
const $=id=>document.getElementById(id);
const els={status:$("appStatus"),board:$("board"),columns:$("columnMoves"),gameStatus:$("gameStatus"),red:$("redPlayer"),yellow:$("yellowPlayer"),newGame:$("newGameBtn"),moveReadout:$("moveReadout"),save:$("saveBtn"),export:$("exportBtn"),import:$("importInput"),reset:$("resetBtn"),positions:$("positionsInput"),depth:$("depthInput"),lr:$("learningRateInput"),train:$("trainBtn"),quick:$("quickTrainBtn"),stop:$("stopBtn"),trainState:$("trainState"),progress:$("trainProgress"),trainStats:$("trainStats"),benchmark:$("benchmarkBtn"),benchmarkStatus:$("benchmarkStatus"),benchmarkOpponent:$("benchmarkOpponent"),benchmarkGames:$("benchmarkGames"),benchmarkStats:$("benchmarkStats"),benchmarkCanvas:$("benchmarkCanvas"),networkCanvas:$("networkCanvas"),weightsCanvas:$("weightsCanvas"),layer:$("layerSelect"),neuron:$("neuronInput"),neuronOutput:$("neuronOutput"),neuronStats:$("neuronStats"),activationRows:$("activationRows"),refresh:$("refreshBtn")};
let model=loadModel(), board=newBoard(), player=1, gameOver=false, autoToken=0, trainingWorker=null, benchmarkWorker=null;
let history=loadHistory();

function loadModel(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?deserializePolicy(JSON.parse(raw)):createPolicyModel();}catch(error){console.error(error);return createPolicyModel();}}
function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");}catch{return[];}}
function saveModel(){localStorage.setItem(STORAGE_KEY,JSON.stringify(serializePolicy(model)));els.status.textContent=`Saved ${model.training.positions.toLocaleString()} labeled positions`;}
function setModel(next){model=next;saveModel();renderAll();}
function playerKind(){return player===1?els.red.value:els.yellow.value;}
function label(kind){return {human:"Human",solver:"Solver",ai:"AI",random:"Random","engine-random":"Engine + random"}[kind];}
function choose(kind){if(kind==="ai")return choosePolicyMove(model,board,player);if(kind==="solver")return chooseSolverMove(board,player,5);if(kind==="engine-random")return chooseEngineRandomMove(board,player);return chooseRandomMove(board);}

function renderBoard(){
  const cells=[];for(let r=ROWS-1;r>=0;r--)for(let c=0;c<COLS;c++){const value=board[r*COLS+c];cells.push(`<div class="cell ${value===1?"red":value===-1?"yellow":""}"></div>`);}els.board.innerHTML=cells.join("");
  const legal=getLegalMoves(board), human=!gameOver&&playerKind()==="human";
  els.columns.innerHTML=Array.from({length:7},(_,c)=>`<button data-col="${c}" ${human&&legal.includes(c)?"":"disabled"} aria-label="Play column ${c+1}">${c+1}</button>`).join("");
  els.columns.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>playMove(Number(button.dataset.col))));
}

function renderGameInfo(){
  if(!gameOver)els.gameStatus.textContent=`${player===1?"Red":"Yellow"} to move - ${label(playerKind())}`;
  const result=policyForward(model,board,player), legal=getLegalMoves(board);let scores=[];
  try{scores=solverScores(board,player,3);}catch{scores=Array(7).fill(null);}
  let best=null;for(const c of legal)if(best===null||result.probabilities[c]>result.probabilities[best])best=c;
  els.moveReadout.innerHTML=Array.from({length:7},(_,c)=>`<div class="move-score ${c===best?"best":""}"><b>${c+1}</b><br>${legal.includes(c)?(result.probabilities[c]*100).toFixed(1)+"%":"--"}<br><span>${scores[c]===null?"--":scores[c]}</span></div>`).join("");
}

function playMove(col){if(gameOver||!getLegalMoves(board).includes(col))return;const moving=player,row=applyMove(board,col,moving);if(checkWin(board,row,col,moving)){gameOver=true;els.gameStatus.textContent=`${moving===1?"Red":"Yellow"} wins (${label(moving===1?els.red.value:els.yellow.value)})`;}else if(!getLegalMoves(board).length){gameOver=true;els.gameStatus.textContent="Draw";}else player=-player;renderAll();scheduleAuto();}
function newGame(){autoToken++;board=newBoard();player=1;gameOver=false;renderAll();scheduleAuto();}
function scheduleAuto(){const token=++autoToken;if(gameOver||playerKind()==="human")return;setTimeout(()=>{if(token!==autoToken||gameOver)return;playMove(choose(playerKind()));},260);}

function statRows(rows){return rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join("");}
function renderTraining(){const t=model.training;els.trainStats.innerHTML=statRows([["Seen / replay",`${t.positions.toLocaleString()} / ${t.replaySize.toLocaleString()}`],["Optimizer updates",t.updates.toLocaleString()],["Train / validation loss",`${t.averageLoss.toFixed(4)} / ${t.validationLoss?.toFixed(4)??"-"}`],["Best validation",t.bestValidationLoss?.toFixed(4)??"-"],["Teacher agreement",`${(t.teacherAgreement*100).toFixed(1)}%`],["Current learning rate",t.learningRate.toExponential(2)],["Solver depth",t.solverDepth||"-"]]);}

function startTraining(override){if(trainingWorker)return;const positions=override||Math.max(100,Math.min(200000,Number(els.positions.value)||12000));trainingWorker=new Worker("./src/solver-trainer-worker.js",{type:"module"});els.train.disabled=els.quick.disabled=true;els.stop.disabled=false;els.trainState.textContent="Generating + learning";els.progress.value=0;els.status.textContent=`Solver labeling ${positions.toLocaleString()} positions`;
  trainingWorker.onmessage=e=>{const data=e.data;if(data.type==="progress"){els.progress.value=data.completed/data.total;els.trainState.textContent=data.stage||"Generating + learning";els.trainStats.innerHTML=statRows([["Stage progress",data.completed.toLocaleString()+" / "+data.total.toLocaleString()],["Live loss",data.loss?data.loss.toFixed(4):"-"],["Live agreement",data.agreement?`${(data.agreement*100).toFixed(1)}%`:"-"]]);}else if(data.type==="done"){model=deserializePolicy(data.model);finishTraining(data.stopped?"Training stopped":"Training complete");saveModel();renderAll();}else if(data.type==="error"){finishTraining(`Training error: ${data.message}`);}};
  trainingWorker.onerror=e=>finishTraining(`Training error: ${e.message}`);trainingWorker.postMessage({type:"train",model:serializePolicy(model),positions,depth:Number(els.depth.value),learningRate:Number(els.lr.value),batchSize:128,replayCapacity:250000});
}
function finishTraining(message){trainingWorker?.terminate();trainingWorker=null;els.train.disabled=els.quick.disabled=false;els.stop.disabled=true;els.trainState.textContent="Idle";els.status.textContent=message;}

function runBenchmark(){if(benchmarkWorker)return;const games=Math.max(100,Math.min(50000,Number(els.benchmarkGames.value)||5000)),opponent=els.benchmarkOpponent.value;benchmarkWorker=new Worker("./src/solver-benchmark-worker.js",{type:"module"});els.benchmark.disabled=true;els.benchmarkStatus.textContent=`Running ${games.toLocaleString()} games...`;benchmarkWorker.onmessage=e=>{if(e.data.type==="progress"){els.benchmarkStatus.textContent=`Running ${e.data.completed.toLocaleString()} / ${games.toLocaleString()} games...`;return;}if(e.data.type!=="done")return;const result={...e.data.result,positions:model.training.positions,createdAt:Date.now()};history.push(result);history=history.slice(-60);localStorage.setItem(HISTORY_KEY,JSON.stringify(history));benchmarkWorker.terminate();benchmarkWorker=null;els.benchmark.disabled=false;renderBenchmark(result);};benchmarkWorker.onerror=e=>{els.benchmarkStatus.textContent=e.message;benchmarkWorker.terminate();benchmarkWorker=null;els.benchmark.disabled=false;};benchmarkWorker.postMessage({type:"benchmark",model:serializePolicy(model),games,opponent});}
function renderBenchmark(last=history.at(-1)){
  if(last){els.benchmarkStatus.textContent=`Last: ${(last.score*100).toFixed(1)}% score vs ${label(last.opponent)}`;els.benchmarkStats.innerHTML=statRows([["Overall W/D/L",`${last.wins} / ${last.draws} / ${last.losses}`],["Overall score",`${(last.score*100).toFixed(1)}%`],["As Red W/D/L",last.red?`${last.red.wins} / ${last.red.draws} / ${last.red.losses}`:"legacy"],["Red score",last.red?`${(last.red.score*100).toFixed(1)}%`:"-"],["As Yellow W/D/L",last.yellow?`${last.yellow.wins} / ${last.yellow.draws} / ${last.yellow.losses}`:"legacy"],["Yellow score",last.yellow?`${(last.yellow.score*100).toFixed(1)}%`:"-"]]);}else els.benchmarkStats.innerHTML="";
  const canvas=els.benchmarkCanvas,ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,pad=34;ctx.clearRect(0,0,w,h);ctx.fillStyle="#141a1d";ctx.fillRect(0,0,w,h);ctx.font="11px system-ui";ctx.strokeStyle="#39444a";ctx.fillStyle="#9eabb1";for(let i=0;i<=4;i++){const y=12+(h-40)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-8,y);ctx.stroke();ctx.fillText(`${100-i*25}%`,2,y+4);}if(!history.length)return;const points=history.slice(-40),maxPos=Math.max(...points.map(p=>p.positions),1),minPos=Math.min(...points.map(p=>p.positions));ctx.strokeStyle="#55b982";ctx.lineWidth=3;ctx.beginPath();points.forEach((p,i)=>{const x=pad+((p.positions-minPos)/Math.max(1,maxPos-minPos))*(w-pad-12),y=12+(1-p.score)*(h-40);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle="#9eabb1";ctx.fillText("labeled positions",w/2-38,h-7);
}

function renderNetwork(){
  const canvas=els.networkCanvas,ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle="#141a1d";ctx.fillRect(0,0,w,h);const boxes=[[18,90,74,82,"2×6×7\ninput"],[112,60,76,142,"64 channel\nstem"],[210,30,105,202,"4 residual\n3×3 blocks"],[342,48,74,76,"policy\n7 cols"],[342,146,74,76,"value\n[-1, 1]"]];ctx.font="12px system-ui";ctx.textAlign="center";for(const[x,y,bw,bh,name]of boxes){ctx.strokeStyle="#55b982";ctx.strokeRect(x,y,bw,bh);ctx.fillStyle="#dbe4e7";name.split("\n").forEach((line,i)=>ctx.fillText(line,x+bw/2,y+bh/2+i*16));}ctx.strokeStyle="#63b9d2";for(const[y1,y2]of[[131,86],[131,184]]){ctx.beginPath();ctx.moveTo(315,131);ctx.lineTo(342,y2);ctx.stroke();}ctx.fillStyle="#9eabb1";ctx.fillText(`${parameterCount(model).toLocaleString()} parameters`,w-70,250);renderWeights();renderActivations();
}
function renderWeights(){const layers=modelLayers(model),li=Math.min(Number(els.layer.value),layers.length-1),layer=layers[li];els.neuron.max=layer.outputSize-1;const neuron=Math.min(Number(els.neuron.value),layer.outputSize-1);els.neuron.value=neuron;els.neuronOutput.value=neuron;const stride=layer.inputSize*layer.kernel*layer.kernel,values=layer.weights.slice(neuron*stride,(neuron+1)*stride),canvas=els.weightsCanvas,ctx=canvas.getContext("2d"),cols=Math.ceil(Math.sqrt(values.length)),rows=Math.ceil(values.length/cols),cw=canvas.width/cols,ch=canvas.height/rows,max=Math.max(...values.map(Math.abs),.001);for(let i=0;i<cols*rows;i++){const v=values[i]||0,intensity=Math.round(35+Math.abs(v)/max*220);ctx.fillStyle=v>=0?`rgb(25,${intensity},110)`:`rgb(${intensity},55,65)`;ctx.fillRect((i%cols)*cw,Math.floor(i/cols)*ch,cw+.5,ch+.5);}const mean=values.reduce((a,b)=>a+b,0)/values.length,norm=Math.sqrt(values.reduce((a,b)=>a+b*b,0));els.neuronStats.innerHTML=statRows([["Selected",`Layer ${li+1}, channel ${neuron}`],["Kernel",`${layer.kernel}×${layer.kernel}`],["Bias",layer.biases[neuron].toFixed(5)],["Weight mean",mean.toFixed(5)],["L2 norm",norm.toFixed(4)]]);}
function renderActivations(){const f=policyForward(model,board,player),rows=[];let best=0;for(let c=1;c<COLS;c++)if(f.probabilities[c]>f.probabilities[best])best=c;rows.push(`<div class="activation-row"><span>policy[${best}]</span><div class="activation-bar"><div class="activation-fill" style="width:${f.probabilities[best]*100}%"></div></div><span>${f.probabilities[best].toFixed(4)}</span></div>`);rows.push(`<div class="activation-row"><span>value</span><div class="activation-bar"><div class="activation-fill" style="width:${(f.value+1)*50}%"></div></div><span>${f.value.toFixed(4)}</span></div>`);els.activationRows.innerHTML=rows.join("");}
function renderAll(){renderBoard();renderGameInfo();renderTraining();renderBenchmark();renderNetwork();}

els.newGame.addEventListener("click",newGame);els.red.addEventListener("change",newGame);els.yellow.addEventListener("change",newGame);els.save.addEventListener("click",saveModel);els.reset.addEventListener("click",()=>{if(confirm("Reset weights, replay buffer, optimizer, and validation set?")){localStorage.removeItem(STORAGE_KEY);const worker=new Worker("./src/solver-trainer-worker.js",{type:"module"});worker.postMessage({type:"clear"});worker.onmessage=()=>worker.terminate();model=createPolicyModel();newGame();els.status.textContent="Model and persistent training state reset";}});els.export.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(serializePolicy(model),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`connect4-residual-policy-${model.training.positions}.json`;a.click();URL.revokeObjectURL(url);});els.import.addEventListener("change",()=>{const file=els.import.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{setModel(deserializePolicy(JSON.parse(reader.result)));els.status.textContent=`Imported ${model.training.positions.toLocaleString()} positions`;}catch(e){alert(e.message);}};reader.readAsText(file);});els.train.addEventListener("click",()=>startTraining());els.quick.addEventListener("click",()=>startTraining(2000));els.stop.addEventListener("click",()=>trainingWorker?.postMessage({type:"stop"}));els.benchmark.addEventListener("click",runBenchmark);els.layer.addEventListener("change",()=>{els.neuron.value=0;renderWeights();});els.neuron.addEventListener("input",renderWeights);els.refresh.addEventListener("click",renderNetwork);
renderAll();scheduleAuto();
